#server.port=${PORT:8081}
#server.address=0.0.0.0
#
## MongoDB
#spring.data.mongodb.uri=${MONGO_URI}
#spring.data.mongodb.database=${MONGO_DATABASE:cettex}
#
## MQTT / EMQX
#mqtt.broker=${MQTT_BROKER:tcp://broker.emqx.io:1883}
#mqtt.client-id=${MQTT_CLIENT_ID:spring-water-monitor}
#mqtt.topic.water=${MQTT_TOPIC_WATER:eau/debit}
#mqtt.topic.energy=${MQTT_TOPIC_ENERGY:energie/pzem}
#mqtt.username=${MQTT_USERNAME:}
#mqtt.password=${MQTT_PASSWORD:}
#
## WebSocket / CORS
#app.websocket.allowed-origins=${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:8100,capacitor://localhost,http://localhost}
#
## JWT
#app.jwt.secret=${JWT_SECRET}
#app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:1440}
#
## Mail
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
## Multipart files
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#
## IA service
#ai.service.url=${AI_SERVICE_URL:http://127.0.0.1:8000}
#
## Logs
#debug=false
#logging.level.org.springframework.boot.web=INFO
#logging.level.org.apache.catalina=INFO
#
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server.port=8081

# Mongo
spring.data.mongodb.uri=mongodb+srv://cettex:cettex@cluster0.k6fpuci.mongodb.net/cettex?retryWrites=true&w=majority
spring.data.mongodb.database=cettex

# =========================
# MQTT / EMQX
# =========================
mqtt.broker=tcp://broker.emqx.io:1883
mqtt.client-id=spring-water-monitor
mqtt.topic.water=eau/debit
mqtt.topic.energy=energie/pzem
mqtt.username=
mqtt.password=

# =========================
# WebSocket
# =========================
app.websocket.allowed-origins=http://localhost:8100,http://192.168.8.106:8100,http://192.168.0.71:8100,capacitor://localhost,http://localhost

# JWT
app.jwt.secret=jkdbvgohserbgoshbeo pKKKKVVVVVVGRANDOM_SECRET_64_CHARACTERS_MINIMUM_ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
app.jwt.expiration-minutes=1440
server.address=0.0.0.0


debug=true
logging.level.org.springframework.boot.web=DEBUG
logging.level.org.apache.catalina=DEBUG


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=projetpfa2025@gmail.com
spring.mail.password=czpz ddcz jada mgyr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
ai.service.url=http://127.0.0.1:8000
